flowchart TD;

Princeton-.maintains..->sftp[(SFTP server)]
Princeton-.contracts with.->Lyrasis
Princeton-.contracts with.->HM

Lyrasis-.maintains.->ASserver[(ASpace Server)]
Lyrasis-.installs.->plugin1
Lyrasis-.installs.->plugin2

HM[Hudson Molonglo]-.develops..->plugin1([user_defined_in_basic])
HM[Hudson Molonglo]-.develops.->plugin2([as_marcao])

ASserver-.runs.->D{{Docker}}
ASserver==sends data==>sftp

D-.runs.->AS(((ArchivesSpace)))
plugin1-.modifies behavior.->plugin2
plugin1--plugs into-->AS

plugin2--plugs into-->AS
plugin2==stores data==>ASserver
